[rospy.client][INFO] 2017-10-13 16:43:00,628: init_node, name[/distance_collector], pid[6167]
[xmlrpc][INFO] 2017-10-13 16:43:00,629: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-13 16:43:00,629: ROS Slave URI: [http://wks-51-57:38568/]
[xmlrpc][INFO] 2017-10-13 16:43:00,629: Started XML-RPC server [http://wks-51-57:38568/]
[rospy.impl.masterslave][INFO] 2017-10-13 16:43:00,629: _ready: http://wks-51-57:38568/
[xmlrpc][INFO] 2017-10-13 16:43:00,629: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-13 16:43:00,630: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-10-13 16:43:00,729: registered with master
[rospy.rosout][INFO] 2017-10-13 16:43:00,729: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-13 16:43:00,732: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-13 16:43:00,733: initializing /clock core topic
[rospy.simtime][INFO] 2017-10-13 16:43:00,735: connected to core topic /clock
[rospy.internal][INFO] 2017-10-13 16:43:00,946: topic[/all_distances] adding connection to [http://wks-51-57:39674/], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,030: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-13 16:43:01,062: topic[/all_distances] adding connection to [http://wks-51-57:40816/], count 1
[rospy.internal][INFO] 2017-10-13 16:43:01,376: topic[/clock] adding connection to [http://wks-51-57:40214/], count 0
[rospy.internal][WARNING] 2017-10-13 16:45:45,170: Unknown error initiating TCP/IP socket to wks-51-57:38226 (http://wks-51-57:39674/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-10-13 16:45:45,170: topic[/all_distances] removing connection to http://wks-51-57:39674/
[rospy.core][INFO] 2017-10-13 16:45:45,171: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-13 16:45:45,180: Unable to initiate TCP/IP socket to wks-51-57:40762 (http://wks-51-57:40816/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-13 16:45:45,182: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-13 16:45:45,183: topic[/clock] removing connection to http://wks-51-57:40214/
[rospy.topics][ERROR] 2017-10-13 16:45:45,184: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-13 16:45:45,184: topic[/all_distances] removing connection to http://wks-51-57:40816/
[rospy.impl.masterslave][INFO] 2017-10-13 16:45:45,184: signal-2
[rospy.internal][WARNING] 2017-10-13 16:45:45,184: Unknown error initiating TCP/IP socket to wks-51-57:49725 (http://wks-51-57:40214/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2017-10-13 16:45:45,800: signal_shutdown [atexit]
